name: "Release Tools for bash"
description: "Installs release tools in a GitHub workflow"
author: "Mihai Bojin <mihai.bojin@gmail.com>"
inputs:
  version:
    description: "The version to install, defaults to the latest release"
    required: false
    default: "v0.0.12"

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        if ! command -v pip >/dev/null 2>&1; then
          echo "WARN: pip is not installed or not found in PATH." >&2
        else
          echo "Installing required dependencies..." >&2
          pip install --user -r ${{ github.action_path }}/requirements.txt
        fi

    - name: Install the release tools
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: |
        ${{ github.action_path }}/scripts/action-install.sh
